### PR TITLE
Expose root dir

### PR DESCRIPTION
**Pull request by EricDriussi**
Following the conversation in #5 I gave it a try and found out that the information seems to be already there and only needs to be formatted and exposed.

This might be one way to go about it, but please keep in mind that my knowledge of Lua is rather lack luster.
There's probably a much better way to do this.

I'll be happy to follow your suggestions and update the docs if needed!

### CODE REVIEW

**Comment by notjedi** [comment]
making the function `get_root` global would suffice afaik. we can just make that function global and everyone can use it and script it on their local machine. that would be good idea ig, what do you think? also there's no need to print the current dir, returning the value makes it more extendable.

**Comment by EricDriussi** [comment]
Well, that makes perfect sense and seems even simpler!

**Comment by EricDriussi** [comment]
Sorry, I can't seem to find the comment 😕

**Comment by notjedi** [comment]
sorry my bad, i meant the review comment as the comment

**Comment by EricDriussi** [comment]
Am I looking in the wrong place? I can't see any review comment.
image

**Comment by notjedi** [comment]
image

**Comment by EricDriussi** [comment]
Unfortunately I still cannot see the comment or mark it as fixed, could the 'pending' tag indicate that the review process is still open? Maybe that's why it doesn't show up for me :thinking:

**Comment by notjedi** [comment]
@EricDriussi thanks for contributing

**Pull request merged**
